services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_nana_mimi
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nana_e_mimi
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
